version: '3'
services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
  redis:
    image: "redis:5.0.4"
    ports:
      - "6379:6379"
  mysql:
    image: "mysql:8.0.15"
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
    ports:
      - "3306:3306"
    volumes:
      - /opt/mysql:/var/lib/mysql/
