version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      ports:
        - "8080:80"
      command: apt install mc
  redis:
    image: "redis:5.0.4"
    ports:
      - "6379:6379"
  mysql:
    command: mysql
    image: mysql:8.0.15
    ports:
      - "3306:3306"
    volumes:
      - /opt/mysql:/var/lib/mysql/
